# Loads default set of integrations. Do not remove.
default_config:
#my:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
template: !include templates.yaml

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24

# # Example configuration.yaml entry
# google_assistant:
#   project_id: static-welder-410904
#   service_account: !include SERVICE_ACCOUNT.JSON
#   report_state: true

# Example configuration.yaml entry
sensor: !include sensors.yaml

homeassistant:
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 192.168.50.0/24
        - fd00::/8
#camera:
#  - platform: xiaomi_cloud_map_extractor
#    host: !secret xiaomi_vacuum_host
#    token: !secret xiaomi_vacuum_token
#    username: !secret xiaomi_cloud_username
#    password: !secret xiaomi_cloud_password
#    draw: ['all']
#    attributes:
#      - calibration_points

notify:
  - platform: group
    name: "Notify Home"
    services:
      - service: living_room_tv
        data:
          data:
            duration: 400
            position: "bottom-left"
            fontsize: "medium"
            transparency: "75%"
            color: "teal"
            interrupt: 0
      - service: spare_room_tv
        data:
          data:
            duration: 4
            position: "bottom-left"
            fontsize: "medium"
            transparency: "75%"
            color: "teal"
            interrupt: 0
      - service: mobile_app_office_tablet
        data:
          data:
            ttl: 0
            priority: high
      - service: mobile_app_kitchen_tablet
        data:
          data:
            ttl: 0
            priority: high
  - platform: group
    name: "Notify Joel"
    services:
      - service: mobile_app_joel_s_s24_ultra
        data:
          data:
            ttl: 0
            priority: high
      - service: mobile_app_joel_galaxy_watch6
        data:
          data:
            ttl: 0
            priority: high
  - platform: group
    name: "Notify All People"
    services:
      - service: notify_joel
  - platform: group
    name: "Notify All"
    services:
      - service: notify_all_people
      - service: notify_home

shell_command:
  setup_tesla_key: >-
    python3 -c "import base64; exec(base64.b64decode('aW1wb3J0IG9zLGpzb24KcD0iL2NvbmZpZy9jdXN0b21fY29tcG9uZW50cy90ZXNsYV9rZXkiCm9zLm1ha2VkaXJzKHAsZXhpc3Rfb2s9VHJ1ZSkKaW5pdF9jb2RlPSIiImZyb20gaG9tZWFzc2lzdGFudC5jb21wb25lbnRzLmh0dHAgaW1wb3J0IEhvbWVBc3Npc3RhbnRWaWV3CmZyb20gYWlvaHR0cC53ZWIgaW1wb3J0IFJlc3BvbnNlCkRPTUFJTj0idGVzbGFfa2V5Igphc3luYyBkZWYgYXN5bmNfc2V0dXAoaGFzcyxjb25maWcpOgogICAgaGFzcy5odHRwLnJlZ2lzdGVyX3ZpZXcoVGVzbGFQdWJsaWNLZXlWaWV3KCkpCiAgICByZXR1cm4gVHJ1ZQpjbGFzcyBUZXNsYVB1YmxpY0tleVZpZXcoSG9tZUFzc2lzdGFudFZpZXcpOgogICAgdXJsPSIvLndlbGwta25vd24vYXBwc3BlY2lmaWMvY29tLnRlc2xhLjNwLnB1YmxpYy1rZXkucGVtIgogICAgbmFtZT0idGVzbGE6cHVibGljX2tleSIKICAgIHJlcXVpcmVzX2F1dGg9RmFsc2UKICAgIGFzeW5jIGRlZiBnZXQoc2VsZixyZXF1ZXN0KToKICAgICAgICBrZXk9Ii0tLS0tQkVHSU4gUFVCTElDIEtFWS0tLS0tXFxuTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFZk4vaWhQMVBCZ21nTWdTa2VEUGNYUjlFS08xRVxcbnFJbmk0Q2JCcUUzdE4rRUZRZ2VlVXdhT0RiSXdXMkFuLzlhSVY1UXc0bmFlMFpYRnBXK21Wa3pwY2c9PVxcbi0tLS0tRU5EIFBVQkxJQyBLRVktLS0tLVxcbiIKICAgICAgICByZXR1cm4gUmVzcG9uc2UodGV4dD1rZXksY29udGVudF90eXBlPSJ0ZXh0L3BsYWluIikKIiIiCndpdGggb3BlbihwKyIvX19pbml0X18ucHkiLCJ3IikgYXMgZjoKICAgIGYud3JpdGUoaW5pdF9jb2RlKQp3aXRoIG9wZW4ocCsiL21hbmlmZXN0Lmpzb24iLCJ3IikgYXMgZjoKICAgIGpzb24uZHVtcCh7ImRvbWFpbiI6InRlc2xhX2tleSIsIm5hbWUiOiJUZXNsYSBLZXkgSG9zdCIsInZlcnNpb24iOiIxLjAuMCIsInJlcXVpcmVtZW50cyI6W10sImRlcGVuZGVuY2llcyI6WyJodHRwIl0sImNvZGVvd25lcnMiOltdfSxmKQpwcmludCgiZG9uZSIp').decode())"

tesla_key:
